### ISSUE TITLE
Fully Operation Examples?

### ISSUE THREAD

**Issue by artbikes** [thegoodideaco/visualizing-hierarchies#2]
Loved your talk but I couldn't quite follow along in real time.
Would it be possible to post a branch with the completed examples in it?

Thanks!

**Comment by thegoodideaco** [comment]
Absolutely!! There are working examples by Ctrl clicking on the menu

**Comment by thegoodideaco** [comment]
Going to close this for now since the full examples are available upon ctrl + clicking the menu. I will add this information to the readme
